name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/Backend.Api/Backend.Api.csproj
      - name: Build
        run: dotnet build src/Backend.Api/Backend.Api.csproj --no-restore
      # - name: Push to ECR
      #   run: echo "Docker build and push to ECR here"
      # - name: Update GitOps repo
      #   run: echo "Update Kustomize image tag here"